{
 "title": "Project_Analysis",
 "tags": [ "zentao" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "SELECT NAME FROM zt_product WHERE `status`= 'normal';"
   },
   {
    "name": "product_id",
    "label": "product_id",
    "query": "SELECT id FROM zt_product WHERE `name`='${project}';"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as '累计Bug总数'  FROM zt_bug where product=${product_id} and deleted='0';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '致命' FROM zt_bug where product=${product_id} and deleted='0' and severity='1';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '严重' FROM zt_bug where product=${product_id} and deleted='0'and severity='2';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '一般' FROM zt_bug where product=${product_id} and deleted='0'and  severity='3';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '提示' FROM zt_bug where product=${product_id} and deleted='0'and severity='4';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where product=${product_id} and deleted='0') as '致命占比' FROM zt_bug where product=${product_id} and deleted='0' and severity='1';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where product=${product_id} and deleted='0') as '严重占比' FROM zt_bug where product=${product_id} and deleted='0' and severity='2';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where product=${product_id} and deleted='0') as '一般占比' FROM zt_bug where product=${product_id} and deleted='0' and severity='3';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where product=${product_id} and deleted='0') as '提示占比' FROM zt_bug where product=${product_id} and deleted='0' and severity='4';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as '今日新增' FROM zt_bug where product=${product_id} and deleted='0'and date(openedDate)=curdate();"
    },
    {
     "rawSql": "SELECT COUNT(*) as '致命' FROM zt_bug where product=${product_id} and deleted='0'and date(openedDate)=curdate() and severity='1';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '严重' FROM zt_bug where product=${product_id} and deleted='0'and date(openedDate)=curdate() and severity='2';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '一般' FROM zt_bug where product=${product_id} and deleted='0'and date(openedDate)=curdate() and severity='3';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '提示' FROM zt_bug where product=${product_id} and deleted='0'and date(openedDate)=curdate() and severity='4';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as '今日关闭' FROM zt_bug where product=${product_id} and deleted='0'and date(closedDate)=curdate();"
    },
    {
     "rawSql": "SELECT COUNT(*) as '致命' FROM zt_bug where product=${product_id} and deleted='0'and date(closedDate)=curdate() and severity='1';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '严重' FROM zt_bug where product=${product_id} and deleted='0'and date(closedDate)=curdate() and severity='2';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '一般' FROM zt_bug where product=${product_id} and deleted='0'and date(closedDate)=curdate() and severity='3';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '提示' FROM zt_bug where product=${product_id} and deleted='0'and date(closedDate)=curdate() and severity='4' and module not REGEXP '${except_id}';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as '累计未关闭Bug总数' FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\";"
    },
    {
     "rawSql": "SELECT COUNT(*) as '致命' FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\" and severity='1';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '严重' FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\" and severity='2';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '一般' FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\" and severity='3';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '提示' FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\" and severity='4';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\") as '致命占比' FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\" and severity='1';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\") as '严重占比' FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\" and severity='2';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\") as '一般占比' FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\" and severity='3';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\") as '提示占比' FROM zt_bug where product=${product_id} and deleted='0' and status!=\"closed\" and severity='4';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as '激活' FROM zt_bug where product=${product_id} and deleted='0' and status='active';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '已解决待回归'  FROM zt_bug where product=${product_id} and deleted='0' and assignedTo!=\"closed\" and status='resolved';"
    }
   ]
  },
  {
   "title": "所有Bug模块分布",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select 模块, 合计, 致命, 严重, 一般, 提示 from (SELECT m.name as '模块',COUNT(a.new) as '合计',\r\n\tCOUNT(case when a.severity='1' then 1 end) as \"致命\",\r\n\tCOUNT(case when a.severity='2' then 1 end) as \"严重\",\r\n\tCOUNT(case when a.severity='3' then 1 end) as \"一般\",\r\n\tCOUNT(case when a.severity='4' then 1 end) as \"提示\"\r\nfrom(\r\n\tselect case b.module\r\n\twhen '0' then '/' else b.module end as module ,b.severity,m.parent, case when substring(substring_index(m.path,',',2),2) is NULL then 0 else substring(substring_index(m.path,',',2),2) end as new\r\n\tfrom zt_bug b\r\n\tleft JOIN zt_module m\r\n\ton b.module = m.id\r\n\twhere b.product=${product_id} and b.deleted='0') a\r\nINNER JOIN (select id, name from zt_module union select 0, '/（未关联模块）') m\r\non a.new = m.id\r\nGROUP BY a.new) temp \r\norder BY 合计 desc;"
    }
   ]
  },
  {
   "title": "未关闭Bug模块分布",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT m.name as '模块',COUNT(a.new) as '合计',\r\n\tCOUNT(case when a.severity='1' then 1 end) as \"致命\",\r\n\tCOUNT(case when a.severity='2' then 1 end) as \"严重\",\r\n\tCOUNT(case when a.severity='3' then 1 end) as \"一般\",\r\n\tCOUNT(case when a.severity='4' then 1 end) as \"提示\"\r\nfrom(\r\n\tselect case b.module\r\n\twhen '0' then '/' else b.module end as module ,b.severity,m.parent, case when substring(substring_index(m.path,',',2),2) is NULL then 0 else substring(substring_index(m.path,',',2),2) end as new\r\n\tfrom zt_bug b\r\n\tleft JOIN zt_module m\r\n\ton b.module = m.id\r\n\twhere b.product='${product_id}' and b.deleted='0' and b.status!='closed') a\r\nINNER JOIN (select id, name from zt_module union select 0, '/（未关联模块）') m\r\non a.new = m.id\r\nGROUP BY a.new\r\norder by COUNT(a.new) desc;"
    }
   ]
  },
  {
   "title": "版本Bug趋势",
   "type": "graph",
   "description": "统计基于当前日期往前1年内的版本情况。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n\tnow() as time_sec,\r\n  a.new,\r\n  count(*) as 'Ver'\r\nfrom(\r\n\tselect b.module,b.severity,m.name as new, b.assignedTo, m.date\r\n\tfrom zt_bug b\r\n\tINNER JOIN zt_build m\r\n\ton b.openedBuild = m.id\r\n\twhere b.product=${product_id} and b.deleted='0' and m.date>DATE_SUB(CURDATE(), INTERVAL 1 YEAR)) a\r\nGROUP BY a.new\r\nORDER BY a.date desc;"
    }
   ]
  },
  {
   "title": "版本Bug分布",
   "type": "table",
   "description": "统计基于当前日期往前1年内的版本情况。",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT a.new as '模块',\r\n\tCOUNT(case when a.severity='1' then 1 end) as \"致命\",\r\n\tCOUNT(case when a.severity='2' then 1 end) as \"严重\",\r\n\tCOUNT(case when a.severity='3' then 1 end) as \"一般\",\r\n\tCOUNT(case when a.severity='4' then 1 end) as \"提示\",\r\n\tcount(*) as \"合计\",\r\n  COUNT(case when a.severity='1' and a.assignedTo!=\"closed\" then 1 end) as \"未关闭致命\",\r\n\tCOUNT(case when a.severity='2' and a.assignedTo!=\"closed\" then 1 end) as \"未关闭严重\",\r\n\tCOUNT(case when a.severity='3' and a.assignedTo!=\"closed\" then 1 end) as \"未关闭一般\",\r\n\tCOUNT(case when a.severity='4' and a.assignedTo!=\"closed\" then 1 end) as \"未关闭提示\",\r\n\tcount(case when a.status='active' then 1 end) as \"激活的\",\r\n\tcount(case when a.assignedTo!=\"closed\" and a.status='resolved' then 1 end) as \"已解决\",\r\n\tcount(case when a.assignedTo!=\"closed\" then 1 end) as \"未关闭合计\"\r\nfrom(\r\n\tselect b.module,b.severity,m.name as new, b.assignedTo, b.status, m.date\r\n\tfrom zt_bug b\r\n\tINNER JOIN zt_build m\r\n\ton b.openedBuild = m.id\r\n\twhere b.product='${product_id}' and b.deleted='0' and m.date>DATE_SUB(CURDATE(), INTERVAL 1 YEAR)) a\r\nGROUP BY a.new\r\norder BY a.date desc;"
    }
   ]
  },
  {
   "title": "未关闭Bug( 致命&严重)",
   "type": "table-old",
   "description": "仅统计了验证程度为“致命”和“严重”的未关闭Bug。",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT new.id as 'Bug编号', m.name as '所属模块', new.title as '缺陷标题', new.openedBy as '创建者', new.assignedTo as '指派给' , new.severity as '严重程度'\r\nFROM (\r\nSELECT a.id,a.module,a.title,a.openedBy,a.assignedTo,a.severity,case when substring(substring_index(b.path,',',2),2) is NULL then 0 else substring(substring_index(b.path,',',2),2) end as new_module\r\nFROM zt_bug a\r\nLEFT JOIN zt_module b\r\non a.module = b.id\r\nwhere a.product = '${product_id}' and a.deleted='0' and a.status!='closed' and a.severity REGEXP '1|2') new\r\nINNER JOIN (select id, name from zt_module union select 0, '/') m\r\non new.new_module = m.id ORDER BY 严重程度"
    }
   ]
  }
 ]
}