{
 "title": "Sprint_Analysis",
 "time": { "from": "2022-02-16T00:00:00.000Z", "to": "2022-03-22T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "SELECT NAME FROM zt_product WHERE `status`= 'normal';"
   },
   {
    "name": "sprint",
    "query": "select name from  zt_project where deleted=\"0\" and id in (select project from zt_projectproduct where product=(SELECT id FROM zt_product WHERE `name`='${project}')) order by begin desc"
   },
   {
    "name": "sprint_id",
    "query": "SELECT id FROM zt_project WHERE `name`='${sprint}';"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as 'Bug总数'  FROM zt_bug where project=${sprint_id} and deleted='0';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '致命' FROM zt_bug where project=${sprint_id} and deleted='0' and severity='1';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '严重' FROM zt_bug where project=${sprint_id} and deleted='0'and severity='2';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '一般' FROM zt_bug where project=${sprint_id} and deleted='0'and  severity='3';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '提示' FROM zt_bug where project=${sprint_id} and deleted='0'and severity='4';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where project=${sprint_id} and deleted='0') as '致命占比' FROM zt_bug where project=${sprint_id} and deleted='0' and severity='1';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where project=${sprint_id} and deleted='0') as '严重占比' FROM zt_bug where project=${sprint_id} and deleted='0' and severity='2';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where project=${sprint_id} and deleted='0') as '一般占比' FROM zt_bug where project=${sprint_id} and deleted='0' and severity='3';"
    },
    {
     "rawSql": "SELECT COUNT(*)/ (SELECT COUNT(*) FROM zt_bug where project=${sprint_id} and deleted='0') as '提示占比' FROM zt_bug where project=${sprint_id} and deleted='0' and severity='4';"
    }
   ]
  },
  {
   "title": "Bug环境",
   "type": "piechart",
   "description": "理想情况是所有Bug均是发现于测试环境，如果UAT或PRE环境发现较多Bug，那么可能测试不充分，需具体分析原因。",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select now() as time_sec, environment as 'Bug环境', SUM(cnt) as '' from (select \r\n\t CASE  \r\n\t WHEN env='test' THEN '测试环境'\r\n\t WHEN env='uat' THEN 'UAT环境'\r\n\t WHEN env='pre' THEN 'PRE环境'\r\n\t WHEN env='production' THEN '生产环境'\r\n\t WHEN (env is NULL or env='') THEN '未分配' \r\n\t END as 'environment'\r\n\t ,count(*) as 'cnt' from zt_bug where deleted='0' and project=${sprint_id} GROUP BY env) temp GROUP BY environment;"
    }
   ]
  },
  {
   "title": "需求Bug密度",
   "type": "table",
   "description": "如果个别需求发现Bug较多，建议再次回顾该需求，分析引起Bug原因及充分评估需求与设计的影响范围，核实测试是否充分。",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT a.title as '需求',COUNT(a.title) as '合计',\r\n\tCOUNT(case when a.severity='1' then 1 end) as \"致命\",\r\n\tCOUNT(case when a.severity='2' then 1 end) as \"严重\",\r\n\tCOUNT(case when a.severity='3' then 1 end) as \"一般\",\r\n\tCOUNT(case when a.severity='4' then 1 end) as \"提示\"\r\nfrom (select s.title, b.severity from zt_bug b inner join zt_story s on b.story=s.id where b.deleted='0' and b.project=${sprint_id}) a\r\nGROUP BY a.title \r\norder BY COUNT(a.title) DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as '遗留Bug总数' FROM zt_bug where project=${sprint_id} and deleted='0' and assignedTo!=\"closed\";"
    },
    {
     "rawSql": "SELECT COUNT(*) as '致命' FROM zt_bug where project=${sprint_id} and deleted='0' and assignedTo!=\"closed\" and severity='1';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '严重' FROM zt_bug where project=${sprint_id} and deleted='0' and assignedTo!=\"closed\" and severity='2';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '一般' FROM zt_bug where project=${sprint_id} and deleted='0' and assignedTo!=\"closed\" and severity='3';"
    },
    {
     "rawSql": "SELECT COUNT(*) as '提示' FROM zt_bug where project=${sprint_id} and deleted='0' and assignedTo!=\"closed\" and severity='4';"
    }
   ]
  },
  {
   "title": "解决方案",
   "type": "piechart",
   "description": "理想图形样式：仅有“已解决”1种分类，即所有Bug的解决方案均是已解决。\n实际迭代中时常除了已解决类型外，还会有其他类型。如果其他类型占比较高，那就值得做相应的根因分析。例如，解决方案中重复Bug占比较高，则可能在任务分配时存在重叠等，具体分析原因并持续改进。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select now() as time_sec,\r\n\t CASE resolution \r\n\t WHEN 'fixed' THEN '已解决'\r\n\t WHEN 'bydesign' THEN '设计如此'\r\n\t WHEN 'duplicate' THEN '重复Bug'\r\n\t WHEN 'external' THEN '外部原因'\r\n\t WHEN 'postponed' THEN '延期处理'\r\n\t WHEN 'story_chg' THEN '需求变更无需解决'\r\n\t WHEN 'willnotfix' THEN '不予解决'\r\n\t WHEN 'notrepro' THEN '无法重现'\r\n\t WHEN 'tostory' THEN '转为需求'\r\n\t WHEN 'tostory1' THEN '转需求'\r\n\t WHEN '' THEN '遗留Bug'\r\n\t END as '解决方案'\r\n\t ,count(*) as '' from zt_bug where deleted='0' and project=${sprint_id} GROUP BY resolution; "
    }
   ]
  },
  {
   "title": "Bug类型",
   "type": "piechart",
   "description": "不同类型的项目可能Bug类型分布有较大差异，如物联网项目和大数据项目，金融相关项目与OA办公项目等。\n从Bug类型图表中，可以大致了解Bug的分布，哪一类型Bug较多，可以做针对性根因分析。另一方面，如果项目是安全关键的项目，但安全相关的Bug较少，也可向项目组警示做进一步核验。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select now() as time_sec,\r\n\t CASE type \r\n\t WHEN 'codeerror' THEN '开发-代码错误'\r\n\t WHEN 'interface' THEN '开发-优化建议'\r\n\t WHEN 'designdefect' THEN '开发-设计缺陷'\r\n\t WHEN 'functionmissing' THEN '开发-功能缺失'\r\n\t WHEN 'automation' THEN '开发-脚本错误'\r\n\t WHEN 'config' THEN '开发-配置错误'\r\n\t WHEN 'dataerror' THEN '开发-数据问题'\r\n\t WHEN 'standard' THEN '开发-代码规范'\r\n\t WHEN 'compatibilityerror' THEN '开发-兼容问题'\r\n\t WHEN 'performance' THEN '开发-性能问题'\r\n\t WHEN 'security' THEN '开发-安全问题'\r\n\t WHEN 'requirementerror' THEN '需求-需求错误'\r\n\t WHEN 'requirementadvice' THEN '需求-需求建议'\r\n\t WHEN 'requiredchange' THEN '需求-需求变更'\r\n\t WHEN 'requirementadd' THEN '需求-需求新增【客户】'\r\n\t WHEN 'install' THEN '运维-环境相关'\r\n\t WHEN 'others' THEN '其他'\r\n\t WHEN '' THEN '未知类型'\r\n\t END as 'Bug类型'\r\n\t ,count(*) as '' from zt_bug where deleted='0' and project=${sprint_id} GROUP BY type;"
    }
   ]
  },
  {
   "title": "迭代Bug趋势",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "\r\nSELECT \r\n  now() as time_sec,\r\n  DATE_FORMAT(temp3.x_date,'%m.%d'),\r\n  case\r\n  when sum(temp3.cnt) is null then 0\r\n  else temp3.cnt\r\n  end as ''\r\nfrom (\r\nselect temp.x_date, temp2.cnt from (select \r\nx_date\r\nfrom (\r\n    select t.*, t.date1 + INTERVAL (a.a + (10 * b.a) + (100 * c.a)) DAY as x_date\r\n    from (select 0 as a union all select 1 union all select 2 union all select 3 union all select 4 union all select 5 union all select 6 union all select 7 union all select 8 union all select 9) as a\r\n    cross join (select 0 as a union all select 1 union all select 2 union all select 3 union all select 4 union all select 5 union all select 6 union all select 7 union all select 8 union all select 9) as b\r\n    cross join (select 0 as a union all select 1 union all select 2 union all select 3 union all select 4 union all select 5 union all select 6 union all select 7 union all select 8 union all select 9) as c\r\n    join (\r\n        select begin as date1, end as date2 from zt_project where id=${sprint_id}\r\n    ) t\r\n    where t.date1 + INTERVAL (a.a + (10 * b.a) + (100 * c.a)) DAY <= t.date2\r\n) a) temp left join (select SUBSTR(openedDate,1,10) as date_time, count(*) as cnt from zt_bug where deleted='0' and project=${sprint_id} GROUP BY SUBSTR(openedDate,1,10) ORDER BY date_time asc) temp2 on temp.x_date=temp2.date_time ORDER BY temp.x_date asc) temp3\r\nGROUP BY temp3.x_date;"
    }
   ]
  },
  {
   "title": "Bug激活情况",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "\r\nSELECT  Bug编号, case when 所属模块 is NULL then '/' else 所属模块 end as '所属模块', 缺陷标题, 创建人, 指派给, 严重程度, 激活次数 from (SELECT new.id as 'Bug编号', m.name as '所属模块', new.title as '缺陷标题', new.openedBy as '创建人', new.assignedTo as '指派给', new.severity as '严重程度', new.activatedCount as '激活次数'\r\nFROM (\r\nSELECT a.id,a.module,a.title,a.openedBy,a.assignedTo,a.severity, a.activatedCount\r\nFROM zt_bug a\r\nwhere a.project = ${sprint_id} and a.deleted='0' and a.activatedCount > 0\r\n) new\r\nLEFT JOIN zt_module m\r\non new.module = m.id) temp order by 严重程度 asc, 激活次数 desc"
    }
   ]
  }
 ]
}